name: math
version: 1.0.0
description: Math Plugin for PolymorphicBot
dependencies:
  polymorphic_bot:
    git: git://github.com/PolymorphicBot/PolymorphicBot.git
  irc: ">=1.4.5 <1.5.0"
  math_expressions: ">=0.1.0 <0.2.0"